// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Demine: typeof import('./src/components/Demine.vue')['default']
    DemineInfo: typeof import('./src/components/DemineInfo.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    IntroSize: typeof import('./src/components/IntroSize.vue')['default']
  }
}

export { }
