// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DemineInfo: typeof import('./src/components/DemineInfo.vue')['default']
    DemineRoot: typeof import('./src/components/DemineRoot.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
  }
}

export { }
